// Generated by LiveScript 1.5.0
var assert;
assert = require('assert');
describe('Upload', function(_){
  describe("Upload File", function(_){
    it('test', function(done){
      var upload, target;
      upload = require('../index.js');
      target = {
        subdomain: 'usetest',
        permission: 'wrongkey'
      };
      return upload('./index.js', target, function(data){
        console.log(data.url);
        assert.equal(data.err, "no access");
        done();
      });
    });
  });
});