// Generated by LiveScript 1.5.0
var assert, toString$ = {}.toString;
assert = require('assert');
describe('Upload', function(_){
  describe("Upload File", function(_){
    it('test', function(done){
      var upload, target;
      upload = require('../index.js');
      target = {
        subdomain: 'usetest',
        permission: 'wrongkey'
      };
      return upload('./index.js', target, function(data){
        assert.equal(data.err, "no access");
        done();
      });
    });
  });
  describe("Upload File 2", function(_){
    it('test', function(done){
      var upload, target;
      upload = require('../index.js');
      target = {
        subdomain: 'usetest',
        permission: 'asdfasfsa343423qwerAwerewr'
      };
      return upload('./index.js', target, function(data){
        assert.equal(toString$.call(data.url).slice(8, -1) === 'String', true);
        done();
      });
    });
  });
  describe("Upload File 3", function(_){
    it('test', function(done){
      var upload, target;
      upload = require('../index.js');
      target = 'wrongkey@usetest.flyber.net';
      return upload('./index.js', target, function(data){
        assert.equal(data.err, "no access");
        done();
      });
    });
  });
  describe("Upload File 4", function(_){
    it('test', function(done){
      var upload, target;
      upload = require('../index.js');
      target = 'asdfasfsa343423qwerAwerewr@usetest.flyber.net';
      return upload('./index.js', target, function(data){
        assert.equal(toString$.call(data.url).slice(8, -1) === 'String', true);
        done();
      });
    });
  });
});