// Generated by LiveScript 1.5.0
(function(){
  var request, fs, toString$ = {}.toString;
  request = require('request');
  fs = require('fs');
  module.exports = function(input, options, callback){
    var config, stream;
    config = {
      url: "http://" + options.subdomain + ".flyber.net/upload",
      headers: {
        permission: options.permission
      }
    };
    stream = (function(){
      switch (false) {
      case toString$.call(input).slice(8, -1) !== 'String':
        return fs.createReadStream(input);
      default:
        return input;
      }
    }());
    return stream.pipe(request.put(config)).pipe(callback);
  };
}).call(this);
