// Generated by LiveScript 1.5.0
(function(){
  var request;
  request = require('request');
  module.exports = function(stream, options, callback){
    var config;
    config = {
      url: "http://" + options.subdomain + ".flyber.net/upload",
      headers: {
        permission: options.permission
      }
    };
    return stream.pipe(request.put(config)).pipe(callback);
  };
}).call(this);
